### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [er-vaidehi/birthday_promotion_plan#1]
Manifest and init and file names:
1. [shows its a copy](https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/__manifest__.py#L2) start with copyright text.
2. [version should be in 11.0.1.0.1 manner](https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/__manifest__.py#L5)
3. [This](https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/__manifest__.py#L24) is not needed
4. remove 'part of browseinfo' https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/__init__.py#L2 check in all py files.
5. https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/ReadME.txt does not need be there. Repo has readme.md thats enough
5. id should be professionally named. view_partner_inherit_birthday_plan https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/views/res_partner_view.xml#L4
6. You should use a branch name as 11.0 / 12.0 or 13.0  not master.
7. https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/models/res_partner.py#L9 - api.multi isnt needed for v13
8. https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/models/res_partner.py#L19 - The field should rather be a selection where the user value is Jan feb instead of 1, 2 , 3. like [('1','Jan')]
9. You could have used self.env.ref(xml id) : https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/models/res_partner.py#L38
10. minimise the search results by searching birthdaymonth before loop : https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/models/res_partner.py#L27
You can add domain : birthdate_month = datetime.strftime('%m'), saves 5 lines of your code
11. https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/models/res_partner.py#L37 : I wonder when someone's bday will ever match this condition.
You should match only bday month.
12. This should run per month first date : so you can count all month bdays in single calculation, rather than 30 days the same method run for nothing.  https://github.com/er-vaidehi/birthday_promotion_plan/blob/master/birthday_promotion_plan/views/birthday_reminder_cron.xml#L8

**Comment by er-vaidehi** [comment]
Fixed

**Comment by er-vaidehi** [comment]
8) This is in v11.
9) That field is just for developer purpose, User is not supposed to use it.
11) Didn't get it
12) No because if we match only birthday month than the customer whose birthday is on 1st march, he will get the mail on same day, actually the functionality is mail is supposed to be sent for birthday promotions and discounts whose birthday is after the specified range. for suppose use set birthday is on 1st march and promotion range is 10 days then mail should be sent on (1st march - 10 days)  
13) No, as per functionality explained in previous 12th point it seems okay for me

**Comment by er-vaidehi** [comment]
Other are fixed
